"""RAA parallel subgraph package — Section 12 Send routing and strategy execution."""

from raa.graphs.subgraphs.common import (
    ALL_SEND_TARGETS,
    LLM_RAA_A_KEY,
    LLM_RAA_B_KEY,
    LLM_RAA_C_KEY,
    RAA_A_REFERENCES,
    RAA_B_REFERENCES,
    RAA_C_REFERENCES,
    RELATIONSHIP_SCOPE_TABLE,
    SEND_TARGET_RAA_A,
    SEND_TARGET_RAA_B,
    SEND_TARGET_RAA_C,
    STRATEGY_ENTITY_DRIVEN,
    STRATEGY_PATTERN_DRIVEN,
    STRATEGY_SAAM_FIRST,
    STRATEGY_REFERENCE_MANIFEST,
    SubgraphPayload,
    SubgraphStrategy,
    VALID_DIAGRAM_SCOPES,
    arch_fragment_from_dict,
    build_subgraph_prompt,
    execute_strategy_subgraph,
    load_reference_file,
    load_strategy_references,
    validate_parent_links,
    validate_relationship_scopes,
)
from raa.graphs.subgraphs.raa_a import run_raa_a
from raa.graphs.subgraphs.raa_b import run_raa_b
from raa.graphs.subgraphs.raa_c import run_raa_c
from raa.graphs.subgraphs.routing import fan_out_subgraphs

__all__ = [
    "ALL_SEND_TARGETS",
    "LLM_RAA_A_KEY",
    "LLM_RAA_B_KEY",
    "LLM_RAA_C_KEY",
    "RAA_A_REFERENCES",
    "RAA_B_REFERENCES",
    "RAA_C_REFERENCES",
    "RELATIONSHIP_SCOPE_TABLE",
    "SEND_TARGET_RAA_A",
    "SEND_TARGET_RAA_B",
    "SEND_TARGET_RAA_C",
    "STRATEGY_ENTITY_DRIVEN",
    "STRATEGY_PATTERN_DRIVEN",
    "STRATEGY_SAAM_FIRST",
    "STRATEGY_REFERENCE_MANIFEST",
    "SubgraphPayload",
    "SubgraphStrategy",
    "VALID_DIAGRAM_SCOPES",
    "arch_fragment_from_dict",
    "build_subgraph_prompt",
    "execute_strategy_subgraph",
    "fan_out_subgraphs",
    "load_reference_file",
    "load_strategy_references",
    "run_raa_a",
    "run_raa_b",
    "run_raa_c",
    "validate_parent_links",
    "validate_relationship_scopes",
]
